//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Web10.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Web10.Core.Resources.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra , vui lòng liên hệ MISA để được hỗ trợ.
        /// </summary>
        public static string ErrorException_VN {
            get {
                return ResourceManager.GetString("ErrorException_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tượng khen thưởng không được để trống.
        /// </summary>
        public static string ErrorValidate_VN_ApplyObject {
            get {
                return ResourceManager.GetString("ErrorValidate_VN_ApplyObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã danh hiệu đã tồn tại trong hệ thống.
        /// </summary>
        public static string ErrorValidate_VN_DuplicateEmulationCode {
            get {
                return ResourceManager.GetString("ErrorValidate_VN_DuplicateEmulationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã danh hiệu không được phép để trống.
        /// </summary>
        public static string ErrorValidate_VN_EmulationCode {
            get {
                return ResourceManager.GetString("ErrorValidate_VN_EmulationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên danh hiệu không được phép để trống.
        /// </summary>
        public static string ErrorValidate_VN_EmulationName {
            get {
                return ResourceManager.GetString("ErrorValidate_VN_EmulationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại phong trào không được để trống.
        /// </summary>
        public static string ErrorValidate_VN_MovementType {
            get {
                return ResourceManager.GetString("ErrorValidate_VN_MovementType", resourceCulture);
            }
        }
    }
}
